### ISSUE TITLE
generated TypeScript interfaces file doesn't have any exported entities

### ISSUE THREAD

**Issue by akeelnazir** [avantcredit/gql2ts#100]
Command-line: `gql2ts schema.json -o src/app/interfaces.ts`

```
declare namespace GQL {
  interface IGraphQLResponseRoot {
    data?: IQuery | IMutation;
    errors?: Array<IGraphQLResponseError>;
  }
}
```

The types and namespace is in the generated interfaces.ts file, but how can I use those interfaces, since they are not exported.

**Comment by brettjurgens** [comment]
you can do something like `GQL.IGraphQLResponseRoot`

**Comment by akeelnazir** [comment]
As per your medium post at https://medium.com/@brettjurgens/graphql-typescript-strongly-typed-api-responses-f8aea1e81b93, running gql2ts generates a TS file with exported interfaces, which can be then be used in other TS files. Here is a snippet from your post;

```
// graphql typescript definitions
declare module GQL {
  export interface IGraphQLResponseRoot {
    data?: IQuery;
    errors?: Array<IGraphQLResponseError>;
  } ...
}
```

The TS file that I get on running gql2ts doesn't export interfaces, therefore, I can't use these interfaces in my TS files.

**Comment by raysuelzer** [comment]
Hey everyone.  I know this isn't an ideal solution., but there is a way to define your own exporter, which I did to solve this problem.  See the attached file.  To use this I run the following:
`gql2ts schema.json -o ./src/schema.ts -e '/my/full/path/to/custom-exporter/gql2ts'

See attached.
[custom-exporter.zip](https://github.com/avantcredit/gql2ts/files/1396760/custom-exporter.zip)

**Comment by akeelnazir** [comment]
Hi @raysuelzer,

Would it be possible for you to implement the fix in the repo and submit a PR to @brettjurgens ?

Thanks
Akeel

**Comment by brettjurgens** [comment]
sorry for the late reply, been super busy at work.

what we do over here is add the generated file to our type roots, then in any file in the project can reference our stuff like `GQL.IWhatever`.

i.e.

```ts
import { executeGraphQL, CUSTOMER_QUERY } from 'somewhere'
const customer: GQL.ICustomer = executeGraphQL(CUSTOMER_QUERY);
```

**Comment by akeelnazir** [comment]
Thanks @brettjurgens. This works 👍

**Comment by raysuelzer** [comment]
Yeah, I didn't want to put in a PR because I'm not sure what the intended functionality is.  What is nice though is being able to override the defaults!  I also removed prefixing interfaces with `I` because Typescript guidelines recommends against this, but it's all personally preference.

**Comment by ntziolis** [comment]
By using `declare` its not possible to reference these types (including the generated enums) during runtime as declare is only for the typescript compiler and dosen't generate any js.

Why not just exchange `declare` with `export`, this makes sure the namespace actually gets compiled to code.

Should not impact any previous use cases while GREATLY improving usefulness of the lib. We have been manually changing this and it has been working great.

At least provide a flag to let people choose. Otherwise its a single line change.

**Comment by ntziolis** [comment]
Running into issues sue to using of `declare` vs exporting both namespace and individual interfaces, enums etc.

When trying to reference enum values that get generated from graphql schema, they simply do not exist during runtime when using `declare`.

Any chance for you to implement a flag to export everything instead of a declare?
