### ISSUE TITLE
Optional GraphQL arrays are not optional on generated interfaces

### ISSUE THREAD

**Issue by mikfoo** [avantcredit/gql2ts#197]
In my schema I have something like

```
userIds: [ID!]
```

Which should convert to

```
userIds?: Array<ID> | null;
```

But it's converted to

```
userIds: Array<ID>;
```

**Comment by brettjurgens** [comment]
i'll take a look, thanks for the report

**Comment by harshabonthu** [comment]
Isn't this working as expected ?  i.e `userIds: [ID!]` should be converted to `userIds: Array<ID>;` 

To get `userIds?: Array<ID> | null;` schema should be `userIds: [ID]`

**Comment by mikfoo** [comment]
@harshabonthu  The schema would be `userIds: [ID!]!` in that case.  The ! makes it required, without it can return null.

**Comment by Razinsky** [comment]
Hi!

I just updated to 1.10.1 and I'm not sure why we should get this result:

This definition:
```
new GraphQLList(OrderType)
```

was converted to that in version 1.9.0:
```
Array<IOrder> | null;
```
and now is converted to that in version 1.10.1:
```
Array<IOrder | null> | null;
```
I do understand the rationale but for us, defining a type as `[Order]` should mean that this is an array of orders period. Not an array of \*maybe\* orders.

In order to fix it, we would have to change all of our schema definitions to this:
```
new GraphQLList(new GraphQLNonNull(OrderType))
```
which seems redundant and unusual — at least for me and my team.

In the meantime, we'll stick to version 1.9.0 hoping that you guys will agree that enforcing the array type is a bit overkill :)

By the way, `gql2ts` is brilliant and saved us so much development time. Thank you.

**Comment by brettjurgens** [comment]
@Razinsky 

`[Order]` is by definition `Array<IOrder | null> | null` 

here are the variations
```
[Order]   => Array<IOrder | null> | null
[Order!]  => Array<IOrder> | null
[Order]!   => Array<IOrder | null>
[Order!]!  => Array<IOrder>
```

The previous behavior was actually a bug - this now properly matches the [GraphQL spec](http://facebook.github.io/graphql/June2018/#sec-Combining-List-and-Non-Null)

if the array being resolved is `[ order1, order2, order3, order4, null  ]`, and our type definition says the type is `Array<IOrder> | null`, the following code will break (even though it passes the type check phase)

```ts
/* in gql def */
interface IOrder { id: string; /* etc. */ } 
interface ICustomer { orders: Array<IOrder> | null; }

/* in code */
const getOrderIds = (orders: ICustomer['orders']) => orders.map(({ id }) => id)
```

I don't think this is overkill - it's actually accurate

I'd recommend using `new GraphQLList(new GraphQLNonNull(OrderType))` instead. if it's too cumbersome you could make a utility:

```ts
const GraphQLListNonNullEntries = type => new GraphQLList(new GraphQLNonNull(type));
```

hopefully, this explains it better 

p.s. happy to hear this has been useful for your team! 😀
